// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v3/game-service/inner/create": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "内部接口"
                ],
                "summary": "创建",
                "parameters": [
                    {
                        "description": "对弈",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inner.createRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/responses.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/inner.createResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v3/game-service/inner/history/student": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "内部接口"
                ],
                "summary": "学生历史数据",
                "parameters": [
                    {
                        "description": "对弈",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inner.studentHistoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/responses.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/inner.studentHistoryResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v3/game-service/inner/info": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "内部接口"
                ],
                "summary": "信息",
                "parameters": [
                    {
                        "description": "对弈",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/public.GameInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/responses.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/public.GameResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v3/game-service/inner/maintain/check": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "内部接口"
                ],
                "summary": "检查对弈维护",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/responses.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/maintain.MaintainResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v3/game-service/inner/rule": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "内部接口"
                ],
                "summary": "规则",
                "parameters": [
                    {
                        "description": "规则",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inner.ruleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/responses.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/inner.ruleResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v3/game-service/inner/score/start": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "内部接口"
                ],
                "summary": "开始数目",
                "parameters": [
                    {
                        "description": "对弈",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AnalysisScoreRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/v3/game-service/public/admin/battle/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "用户的对弈",
                "parameters": [
                    {
                        "type": "string",
                        "name": "business_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "筛选开始时间 区间A",
                        "name": "start_at_begin",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "筛选开始时间 区间B",
                        "name": "start_at_end",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "学习卡号",
                        "name": "user_account",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户真实姓名",
                        "name": "user_actual_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户名 手机号",
                        "name": "user_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户昵称",
                        "name": "user_nick_name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/responses.PageResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "results": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/public.battleResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v3/game-service/public/admin/game/business-view": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "对弈数据",
                "parameters": [
                    {
                        "description": "对弈",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/public.businessViewRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/public.businessTypeView"
                            }
                        }
                    }
                }
            }
        },
        "/api/v3/game-service/public/admin/game/check-maintain": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "检查对弈维护",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/maintain.MaintainResponse"
                        }
                    }
                }
            }
        },
        "/api/v3/game-service/public/admin/game/info": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "对弈管理",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "game_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/public.GameResponse"
                        }
                    }
                }
            }
        },
        "/api/v3/game-service/public/admin/game/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "对弈管理",
                "parameters": [
                    {
                        "type": "string",
                        "name": "business_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "筛选开始时间 区间A",
                        "name": "start_at_begin",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "筛选开始时间 区间B",
                        "name": "start_at_end",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "territory captured",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/responses.PageResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "results": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/public.GameResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v3/game-service/public/admin/game/maintain": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "对弈维护",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v3/game-service/public/admin/game/sgf": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "对弈管理",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "game_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/public.SGFResponse"
                        }
                    }
                }
            }
        },
        "/api/v3/game-service/public/admin/game/un-maintain": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "解除对弈维护",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v3/game-service/public/app/battle/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "APP"
                ],
                "summary": "我的对弈",
                "parameters": [
                    {
                        "type": "string",
                        "name": "business_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "筛选开始时间 区间A",
                        "name": "start_at_begin",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "筛选开始时间 区间B",
                        "name": "start_at_end",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "学习卡号",
                        "name": "user_account",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户真实姓名",
                        "name": "user_actual_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户名 手机号",
                        "name": "user_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户昵称",
                        "name": "user_nick_name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/responses.PageResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "results": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/public.battleResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v3/game-service/public/app/game/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "APP"
                ],
                "summary": "对弈大厅",
                "parameters": [
                    {
                        "type": "string",
                        "name": "business_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "筛选开始时间 区间A",
                        "name": "start_at_begin",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "筛选开始时间 区间B",
                        "name": "start_at_end",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "territory captured",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/responses.PageResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "results": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/public.GameResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v3/game-service/public/app/game/maintain": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "APP"
                ],
                "summary": "检查是否维护中",
                "parameters": [
                    {
                        "type": "string",
                        "name": "business_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "筛选开始时间 区间A",
                        "name": "start_at_begin",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "筛选开始时间 区间B",
                        "name": "start_at_end",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "territory captured",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/maintain.MaintainResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "inner.createRequest": {
            "type": "object",
            "required": [
                "black_user_id",
                "black_user_type",
                "board_size",
                "business_type",
                "sgf",
                "white_user_id",
                "white_user_type"
            ],
            "properties": {
                "black_byo_yomi": {
                    "type": "integer"
                },
                "black_byo_yomi_time": {
                    "type": "integer"
                },
                "black_enter": {
                    "type": "boolean"
                },
                "black_return_stone": {
                    "type": "number"
                },
                "black_time": {
                    "type": "integer"
                },
                "black_user_account": {
                    "type": "string"
                },
                "black_user_actual_name": {
                    "type": "string"
                },
                "black_user_avatar": {
                    "type": "string"
                },
                "black_user_extra": {
                    "description": "附加信息",
                    "type": "string"
                },
                "black_user_id": {
                    "type": "string"
                },
                "black_user_level": {
                    "type": "string"
                },
                "black_user_name": {
                    "type": "string"
                },
                "black_user_nick_name": {
                    "type": "string"
                },
                "black_user_type": {
                    "description": "1 玩家 2 假人 3 AI",
                    "type": "integer"
                },
                "board_size": {
                    "description": "9 13 19",
                    "type": "integer"
                },
                "business_type": {
                    "description": "业务类型",
                    "type": "string"
                },
                "can_start_time": {
                    "type": "integer"
                },
                "enable_move_time": {
                    "description": "是否开启第一步倒计时 0 否 1 是",
                    "type": "integer"
                },
                "end_time": {
                    "type": "integer"
                },
                "is_end": {
                    "type": "boolean"
                },
                "is_start": {
                    "type": "boolean"
                },
                "max_step": {
                    "description": "最大步数",
                    "type": "integer"
                },
                "not_enter_time": {
                    "description": "一方未进入或两方都未进入 强制结束时间",
                    "type": "integer"
                },
                "sgf": {
                    "type": "string"
                },
                "start_time": {
                    "type": "integer"
                },
                "step": {
                    "type": "integer"
                },
                "territory_step": {
                    "type": "integer"
                },
                "white_byo_yomi": {
                    "type": "integer"
                },
                "white_byo_yomi_time": {
                    "type": "integer"
                },
                "white_time": {
                    "type": "integer"
                },
                "white_user_account": {
                    "type": "string"
                },
                "white_user_actual_name": {
                    "type": "string"
                },
                "white_user_avatar": {
                    "type": "string"
                },
                "white_user_enter": {
                    "type": "boolean"
                },
                "white_user_extra": {
                    "type": "string"
                },
                "white_user_id": {
                    "type": "string"
                },
                "white_user_level": {
                    "type": "string"
                },
                "white_user_name": {
                    "type": "string"
                },
                "white_user_nick_name": {
                    "type": "string"
                },
                "white_user_type": {
                    "description": "1 玩家 2 假人 3 AI",
                    "type": "integer"
                },
                "win": {
                    "description": "0 无 1 黑 2 白 3 和 4 双方弃权",
                    "type": "integer"
                },
                "win_captured": {
                    "description": "赢棋子数",
                    "type": "integer"
                },
                "win_result": {
                    "description": "输赢原因 B+2.5 黑胜2.5目 W+2.5 白胜2.5目 B+R 黑胜白认输 B+T 黑胜白超时 W+R 白胜黑认输 W+T 白胜黑超时 B+C1 黑胜吃1子 W+C1 白胜吃一子 B+L 黑胜白未参加 W+L  白胜黑未参加 B+A 黑胜仲裁 W+A 白胜仲裁 Draw 和 Abstain 弃权",
                    "type": "string"
                }
            }
        },
        "inner.createResponse": {
            "type": "object",
            "properties": {
                "game_id": {
                    "type": "integer"
                }
            }
        },
        "inner.ruleRequest": {
            "type": "object",
            "required": [
                "board_size",
                "type"
            ],
            "properties": {
                "board_size": {
                    "description": "9 13 19",
                    "type": "integer"
                },
                "handicap_count": {
                    "description": "让子 0 不让 1 让先 其他让子数",
                    "type": "integer"
                },
                "type": {
                    "description": "1 吃子 2 围地",
                    "type": "integer"
                },
                "win_captured": {
                    "type": "integer"
                }
            }
        },
        "inner.ruleResponse": {
            "type": "object",
            "properties": {
                "black_return_stone": {
                    "type": "number"
                },
                "max_step": {
                    "type": "integer"
                },
                "sgf": {
                    "type": "string"
                },
                "territory_step": {
                    "type": "integer"
                }
            }
        },
        "inner.studentHistoryRequest": {
            "type": "object",
            "properties": {
                "end_date": {
                    "type": "integer"
                },
                "start_date": {
                    "type": "integer"
                },
                "student_id": {
                    "type": "integer"
                }
            }
        },
        "inner.studentHistoryResponse": {
            "type": "object",
            "properties": {
                "black_lose": {
                    "description": "执黑输数量",
                    "type": "integer"
                },
                "black_win": {
                    "description": "/执黑赢数量",
                    "type": "integer"
                },
                "cost": {
                    "description": "花费时间 秒",
                    "type": "integer"
                },
                "label_name": {
                    "description": "对弈类型",
                    "type": "string"
                },
                "white_lose": {
                    "description": "执白输数量",
                    "type": "integer"
                },
                "white_win": {
                    "description": "执白赢数量",
                    "type": "integer"
                }
            }
        },
        "maintain.MaintainResponse": {
            "type": "object",
            "properties": {
                "is_maintain": {
                    "type": "boolean"
                }
            }
        },
        "public.GameInfoRequest": {
            "type": "object",
            "required": [
                "game_id"
            ],
            "properties": {
                "game_id": {
                    "type": "integer"
                }
            }
        },
        "public.GameResponse": {
            "type": "object",
            "properties": {
                "black_byo_yomi": {
                    "description": "黑方初始读秒",
                    "type": "integer"
                },
                "black_byo_yomi_time": {
                    "description": "黑方初始读秒时间",
                    "type": "integer"
                },
                "black_enter": {
                    "type": "boolean"
                },
                "black_time": {
                    "description": "黑方初始时间",
                    "type": "integer"
                },
                "black_user_account": {
                    "type": "string"
                },
                "black_user_actual_name": {
                    "type": "string"
                },
                "black_user_avatar": {
                    "type": "string"
                },
                "black_user_id": {
                    "type": "string"
                },
                "black_user_level": {
                    "type": "string"
                },
                "black_user_name": {
                    "type": "string"
                },
                "black_user_nick_name": {
                    "type": "string"
                },
                "black_user_type": {
                    "description": "1 玩家 2 假人 3 AI",
                    "type": "integer"
                },
                "board_size": {
                    "description": "棋盘尺寸",
                    "type": "integer"
                },
                "business_type": {
                    "description": "业务类型",
                    "type": "string"
                },
                "can_start_time": {
                    "type": "integer"
                },
                "end_time": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "is_end": {
                    "type": "boolean"
                },
                "is_start": {
                    "type": "boolean"
                },
                "km": {
                    "description": "贴目",
                    "type": "number"
                },
                "left_black_byo_yomi": {
                    "description": "黑方剩余读秒次数",
                    "type": "integer"
                },
                "left_black_byo_yomi_time": {
                    "description": "黑方剩余读秒时间",
                    "type": "integer"
                },
                "left_black_time": {
                    "description": "黑方剩余时间",
                    "type": "integer"
                },
                "left_white_byo_yomi": {
                    "description": "白方剩余读秒次数",
                    "type": "integer"
                },
                "left_white_byo_yomi_time": {
                    "description": "白方剩余读秒时间",
                    "type": "integer"
                },
                "left_white_time": {
                    "description": "白方剩余时间",
                    "type": "integer"
                },
                "max_step": {
                    "description": "最大步数",
                    "type": "integer"
                },
                "not_enter_time": {
                    "description": "一方未进入或两方都未进入 强制结束时间",
                    "type": "integer"
                },
                "start_time": {
                    "type": "integer"
                },
                "step": {
                    "type": "integer"
                },
                "view_count": {
                    "description": "观看人数",
                    "type": "integer"
                },
                "white_byo_yomi": {
                    "description": "白方初始读秒",
                    "type": "integer"
                },
                "white_byo_yomi_time": {
                    "description": "白方初始读秒时间",
                    "type": "integer"
                },
                "white_time": {
                    "description": "白方初始时间",
                    "type": "integer"
                },
                "white_user_account": {
                    "type": "string"
                },
                "white_user_actual_name": {
                    "type": "string"
                },
                "white_user_avatar": {
                    "type": "string"
                },
                "white_user_enter": {
                    "type": "boolean"
                },
                "white_user_id": {
                    "type": "string"
                },
                "white_user_level": {
                    "type": "string"
                },
                "white_user_name": {
                    "type": "string"
                },
                "white_user_nick_name": {
                    "type": "string"
                },
                "white_user_type": {
                    "description": "1 玩家 2 假人 3 AI",
                    "type": "integer"
                },
                "win": {
                    "description": "0 无 1 黑 2 白 3 和 4 弃权",
                    "type": "integer"
                },
                "win_captured": {
                    "description": "赢棋子数",
                    "type": "integer"
                },
                "win_result": {
                    "description": "输赢原因 B+2.5 黑胜2.5目 W+2.5 白胜2.5目 B+R 黑胜白认输 B+T 黑胜白超时 W+R 白胜黑认输 W+T 白胜黑超时 B+C1 黑胜吃1子 W+C1 白胜吃一子 B+L 黑胜白未参加 W+L  白胜黑未参加 B+A 黑胜仲裁 W+A 白胜仲裁 Draw 和 Abstain 弃权",
                    "type": "string"
                }
            }
        },
        "public.SGFResponse": {
            "type": "object",
            "properties": {
                "sgf": {
                    "type": "string"
                }
            }
        },
        "public.battleResponse": {
            "type": "object",
            "properties": {
                "board_size": {
                    "type": "integer"
                },
                "business_type": {
                    "description": "业务类型",
                    "type": "string"
                },
                "ended_at": {
                    "type": "integer"
                },
                "game_id": {
                    "type": "integer"
                },
                "opponent_user_account": {
                    "type": "string"
                },
                "opponent_user_actual_name": {
                    "type": "string"
                },
                "opponent_user_avatar": {
                    "type": "string"
                },
                "opponent_user_name": {
                    "type": "string"
                },
                "opponent_user_nick_name": {
                    "type": "string"
                },
                "opponent_user_side": {
                    "description": "1 黑 2 白",
                    "type": "integer"
                },
                "started_at": {
                    "type": "integer"
                },
                "type": {
                    "description": "territory  captured",
                    "type": "string"
                },
                "user_account": {
                    "type": "string"
                },
                "user_actual_name": {
                    "type": "string"
                },
                "user_avatar": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                },
                "user_nick_name": {
                    "type": "string"
                },
                "user_side": {
                    "description": "1 黑 2 白",
                    "type": "integer"
                },
                "user_win": {
                    "description": "1 胜 2 负 3 和 4 弃权",
                    "type": "integer"
                },
                "win_result": {
                    "description": "输赢原因 B+2.5 黑胜2.5目 W+2.5 白胜2.5目 B+R 黑胜白认输 B+T 黑胜白超时 W+R 白胜黑认输 W+T 白胜黑超时 B+C1 黑胜吃1子 W+C1 白胜吃一子 B+L 黑胜白未参加 W+L  白胜黑未参加 B+A 黑胜仲裁 W+A 白胜仲裁 Draw 和 Abstain 弃权",
                    "type": "string"
                }
            }
        },
        "public.businessData": {
            "type": "object",
            "properties": {
                "business_type": {
                    "type": "string"
                },
                "count": {
                    "type": "integer"
                }
            }
        },
        "public.businessTypeView": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/public.businessData"
                    }
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "public.businessViewRequest": {
            "type": "object",
            "required": [
                "end_time",
                "start_time"
            ],
            "properties": {
                "end_time": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "integer"
                }
            }
        },
        "request.AnalysisScoreRequest": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "responses.PageResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "总数",
                    "type": "integer"
                },
                "results": {
                    "description": "数据"
                }
            }
        },
        "responses.StandardResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "0 成功 1失败",
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "description": "提示语",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
